### ISSUE TITLE
xgb.cv.R return cross-validation history

### ISSUE THREAD

**Issue by FeiYeYe** [tqchen/xgboost#114]
Hi, can you make the history available in xgb.cv.R by returning the history object instead of always returning TRUE? Thanks.

**Comment by pommedeterresautee** [comment]
@tqchen I think this feature is correctly implemented for now. If you think it is, don't hesitate to close this issue.

**Comment by tqchen** [comment]
thanks @FeiYeYe  and @pommedeterresautee 's contribution to this thread. Hope this will make xgboost's R package more friendly and we would love to have more users trying it:)

**Comment by pommedeterresautee** [comment]
If you want more users you can communicate more about your work :)

In France there is a Machine learning meetup (from what I understood, it's the biggest one, outside US of course). Every meeting there are 150 seats (and > 200 people of course), > 1700 members, very long waiting list, the meetup can be followed in live on Youtube. Every time there are some remote presentations (Skype). It can be in French or in English. Two meetup ago there was a presentation about random forest implementation in sci-kit (from the author). It would be nice if you want to make a presentation of your tool (there are a part of the French Kaggle community in this meetup). Most people in the public are post doc in Math or Physics (I feel all but me are :-) ) so the level is pretty high sometimes. 

I can contact organizers if you want (to get some basic information). Best you come in Paris and you present your work, or you make a remote presentation.

Your work is pretty awesome, more users, more commits, more improvement for all.

Some address:
http://www.meetup.com/Paris-Machine-learning-applications-group/
http://nuit-blanche.blogspot.fr/p/paris-based-meetups-on-machine-learning.html

**Comment by tqchen** [comment]
Thanks for the suggestion!  I am not sure whether I will present on the meetup. 

But we definitely want to communicate more about it. It would be great if you also introduce the thing to the people you know, and talk about it. You have contributed a lot on this:)

**Comment by pommedeterresautee** [comment]
another way to communicate with potential users:
https://github.com/tqchen/xgboost/issues/158
