### ISSUE TITLE
bug in LamdaRank?

### ISSUE THREAD

**Issue by zhoujj03** [tqchen/xgboost#119]
Recently I read the LamdaRank objective and found the following code:
         // accumulate gradient and hessian in both pid, and nid
          gpair[pos.rindex].grad += g * w;
          gpair[pos.rindex].hess += 2.0f * h;
          gpair[neg.rindex].grad -= g * w;
          gpair[neg.rindex].hess += 2.0f * h;
What I don't understand is the hess here? Why there is no w in the hess calcalation? Where does the 2.0f come from? I think the correct code should be:
         // accumulate gradient and hessian in both pid, and nid
          gpair[pos.rindex].grad += g * w;
          gpair[pos.rindex].hess += w * h;
          gpair[neg.rindex].grad -= g * w;
          gpair[neg.rindex].hess += w * h;

**Comment by tqchen** [comment]
This is now fixed
