### ISSUE TITLE
Documentation of  xgb.DMatrix {xgboost} for categorical input

### ISSUE THREAD

**Issue by pommedeterresautee** [tqchen/xgboost#121]
In R documentation of function xgb.DMatrix, the example doesn't take a real dataset but one already ready.

```
Examples

data(agaricus.train, package='xgboost')
train <- agaricus.train
dtrain <- xgb.DMatrix(train$data, label=train$label)
xgb.DMatrix.save(dtrain, 'xgb.DMatrix.data')
dtrain <- xgb.DMatrix('xgb.DMatrix.data')
```

Example should show how to transform a categorical dataset to a sparse matrix like:
```R
#data is a dataframe with many categorical features
library(Matrix)
X <- sparse.model.matrix(Y~., data = data)
#...
```

**Comment by zhuwenxiang** [comment]
by the way, can xgb.DMatrix format convert to sparse matrix in R? @tqchen @hetong007

**Comment by tqchen** [comment]
@zhuwenxiang currently it is not supported. Is there any reason that you want to support this?

**Comment by pommedeterresautee** [comment]
@zhuwenxiang if you don't know how to proceed, you can check this documentation (not finished):
https://www.dropbox.com/s/bp8x1bmhg1bk9rf/discoverYourData.html?dl=0

**Comment by pommedeterresautee** [comment]
@tqchen I need to add some text to the first vignette released to present the second way to transform categorical data and make it compliant with xgboost but for me this issue is to be closed

**Comment by tqchen** [comment]
Sure, please go ahead and close the issue if you like
