### ISSUE TITLE
different results across different runs with no change in parameters

### ISSUE THREAD

**Issue by jfkingiii** [tqchen/xgboost#13]
I was able to get results that would replicate with xgboost up to 750 trees or so. With these parameters on the Kaggle Higgs boson problem:

param['bst:eta'] = 0.025
param['bst:max_depth'] = 6
param['eval_metric'] = 'auc'
param['silent'] = 1
param['nthread'] = 32
num_round = 1100
threshold_ratio = 0.148

I get slightly different answers each time I run. Code for higgs-numpy.py here:

http://pastebin.com/EEK4FAQK

Code for higgs-pred.py here

http://pastebin.com/hRCL15X2

**Comment by tqchen** [comment]
I will close this feature for now, since it is most likely to be floating point summation issue. The random seed problem is already fixed

**Comment by giuliohome** [comment]
A couple of articles about floating point summation for future reference:
http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.309.6586
http://www.eecs.berkeley.edu/~hdnguyen/public/papers/ARITH21_Fast_Sum.pdf
https://publications.lip6.fr/index.php/publications/show/10315
