### ISSUE TITLE
Getting predicted values from cross-validation.

### ISSUE THREAD

**Issue by hetong007** [tqchen/xgboost#151]
In cross-validation, we use k-1 folds of data as training data and predict on the k-th fold. After k runs, we will have k predictions on each fold. We can further exam this vector, or use this vector to build our ensemble learning machine.

Now it seems that the cpp code for cross-validation is not providing such function.  Which is better, to directly modify the current function, or create new function for this purpose?

**Comment by tqchen** [comment]
I think it have nothing to do with cpp code, it is just R code who call multiple xgboost solvers. Since this is part of R lib, I will leave the interface design to your choice.

**Comment by hetong007** [comment]
The concern is that, if this is solved in R code, that means R is the only wrapper supporting it. I am not sure if cpp/python users have the same need.

**Comment by tqchen** [comment]
It is OK. Because such feature is more like a add-on to the core feature(training/predict) of xgboost. So it is ok for R package to have a function to do that

**Comment by hetong007** [comment]
It is done with [this commit](https://github.com/tqchen/xgboost/commit/eb01acfad84bf4264e19ca39f7d447df05ded9bf).
