### ISSUE TITLE
When does update is planed to be pushed in Cran?

### ISSUE THREAD

**Issue by pommedeterresautee** [tqchen/xgboost#154]
Xgboost is dependant of DiagrammeR package for plotting decision trees.

I have noticed the cleaning in R code. I suppose new version is about to be pushed.

DiagrammeR has evolved a lot since first release (crazy work in this package). Syntax has evolved since I implemented it in Xgboost.

Therefore I need to know if my guess of pushing update of Xgboost is right so I know if I push syntax fix (or even switch to the new functionnalities of this package, new diagrams are much more beautiful and looks more pro).

My issue is that I don't want to make Xgboost dependent to a package version not released on Cran and I don't want the plotting function to be broken after a few days because of DiagrammeR being updated in the meantime...

Best solution: sync both updates :-) or wait they make the first move.

For reference:
https://github.com/rich-iannone/DiagrammeR/issues/53

**Comment by tqchen** [comment]
@hetong007 will be coordinating this. I think we can wait till a version that is nicely complete

**Comment by hetong007** [comment]
@pommedeterresautee There're something I am currently working on as well. So I guess we can wait for their moves first. You could fix/upgrade `xgboost` now, but please pay attention to any changes in their official CRAN version in the future. Thanks!

**Comment by hetong007** [comment]
@pommedeterresautee it would be great if
1. you could edit DESCRIPTION to note the exact version number of the dependencies when new functions are applied here.
2. add your name to the Author in DESCRIPTION.
3. run `roxygen2::roxygenize()` when you finish editting the documentation of the files, so that the `Rd` files under `man` could also be changed.

**Comment by BlindApe** [comment]
Would be possible to have a beta version (R windows) here meanwhile?
I don't know exactly how to make it.
Tong, I would like to test the new splitting all attribute with 'slice' function.

Thanks

**Comment by hetong007** [comment]
@BlindApe If I understand correctly, you can install [RTools](http://cran.r-project.org/bin/windows/Rtools/) on your Win machine and run

```R
require(devtools)
install_github('tqchen/xgboost',subdir='R-package')
```

to install the latest version.

**Comment by BlindApe** [comment]
Thank you

**Comment by hetong007** [comment]
@pommedeterresautee I will merge the pull request once `DiagrammeR` is pushed on CRAN.

**Comment by pommedeterresautee** [comment]
@hetong007 no problem. I follow advancement in DiagrammeR package. FYI I have added a new function in the pull request to plot feature importance.

**Comment by pommedeterresautee** [comment]
DiagrammeR is updated on Cran
http://cran.r-project.org/web/packages/DiagrammeR/index.html
