### ISSUE TITLE
Direct loading of csv/tsv for purely numerical matrices

### ISSUE THREAD

**Issue by hetong007** [tqchen/xgboost#157]
Due to the issue and discussions [here](https://github.com/tqchen/xgboost/issues/156), we might want to have this function when it is slow to transform the data into libsvm format.

Or we can consider wrapping [this official tool](http://www.csie.ntu.edu.tw/%7Ecjlin/libsvm/faq.html#f307) to convert the data file to libsvm format ahead of loading into the memory.

**Comment by tqchen** [comment]
I am closing this issue for now. Since seems the reference issue is resolved by adding better interfacing between R's matrix and data. There are some decisions made by user when loading csv file (which label field, feature encoding) that can be better handled using host language(python R)

**Comment by AbdealiJK** [comment]
I'd like to bring this up again. In the binary (CLI), having the ability to read CSV would be very helpful.

@tqchen I noticed that you created the CSV parser in dmlc-core in Dec 2015 - https://github.com/dmlc/dmlc-core/commits/master/src/data/csv_parser.h

Can we not allow this to be used in xgboost ? It allows users to specify the label column as a parameter. Currently it seems like xgboost forces the format_type to be libsvm.
