### ISSUE TITLE
Support for R's save and load instead of xgb.save

### ISSUE THREAD

**Issue by zachmayer** [tqchen/xgboost#160]
```{R}
library(xgboost)
set.seed(23)
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
train <- agaricus.train
test <- agaricus.test
bst <- xgboost(
  data = train$data, label = train$label, max.depth = 2,
  eta = 1, nround = 2,objective = "binary:logistic")
pred <- predict(bst, test$data)

f <- tempfile()
saveRDS(bst, f)
bst_new = readRDS(f)
unlink(f)
bst_new #NULL pointer
pred2 <- predict(bst_new, test$data) #This line segfaults
```

Not all users will realize they are supposed to use the `xbg.save` and `xgb.load` functions.  Furthermore, if the [caret](https://github.com/berndbischl/mlr) or [mlr](https://github.com/topepo/caret) package is used to cross-validate the model, the final `caret::train` or `mlr::train` object cannot be saved or loaded without triggering a segfault.

Basically, this issue is dangerous to new users and severely limits what advanced users can do with this package.  It would be really nice to find a way to make the final object support serialization through R's `save` and `load` functions.

**Comment by tqchen** [comment]
We did not do this due to technical reason. The model structure is wrapped and maintained by C++ side and not exposed in the R side.

We will be able to do this if we can find someway to hook R's save and load functions, to support customized serialization for the Booster datatype(to/from raw bytes). But seems such function do not exist.

**Comment by zachmayer** [comment]
I've successfully used:xgb.save

readBin

save

load

xgb.save

xgb.load




To save the model as an R object then load it.  I'll post the exact code shortly, but you can store the model as a raw vector in R.  It's just cumbersome!


—

**Comment by pommedeterresautee** [comment]
@zachmayer Hi, I see you are a kind of caret expert.
We are starting to writing some R vignette for this package. I think it would be good to have a word on how to make xgboost interact with caret and your own package. I have no experience for that. If you can provide very basic guidelines it would be very helpful for the documentation to come.

Another thing I am thinking is a fair performance comparaison through caret between xgboost and gbm. Do you think it s possible? 

Kind regards,
Michaël

**Comment by zachmayer** [comment]
I'm actually working on integrating `xgboost` and caret right now!  The main problem I'm having is that you can't save caret objects after fitting an xgboost model, because caret doesn't know to use `xgboost.save` instead of base R save.

**Comment by zachmayer** [comment]
Here's my hack to save an load an xgboost model in base R.  I really dislike it, as I have to use 3 tempfiles to do it, but it works:

```{R}
#Fit a model
library(xgboost)
set.seed(23)
data(agaricus.train, package='xgboost')
data(agaricus.test, package='xgboost')
train <- agaricus.train
test <- agaricus.test
bst <- xgboost(
  data = train$data, label = train$label, max.depth = 2,
  eta = 1, nround = 2,objective = "binary:logistic")
pred <- predict(bst, test$data)

#Hack to save an xgboost model
f1 <- tempfile()
f2 <- tempfile()
xgb.save(bst, f1)
model_raw_bytes <- readBin(f1, what='raw', file.info(f)[1, "size"])
unlink(f1)
print(head(model_raw_bytes))
saveRDS(model_raw_bytes, f2)

#Hack to load an xgboost
f3 <- tempfile()
model_raw_bytes <- readRDS(f2)
writeBin(model_raw_bytes, f3)
model_2 <- xgb.load(f3)
pred_2 <- predict(model_2, test$data)
all.equal(pred_2, pred)
unlink(f2)
unlink(f3)
```

Is there a way to pull the raw bytes of the `xgboost` model into R's memory, without first writing them to the disk?

**Comment by tqchen** [comment]
Yes, I think so. It is possible to pull xgb'a model into a raw array. Will
keep you updated once the function is ready

On Sunday, February 1, 2015, Zach Mayer <notifications@github.com> wrote:

> Here's my hack to save an load an xgboost model in base R. I really
> dislike it, as I have to use 3 tempfiles to do it, but it works:
>
> #Fit a model
> library(xgboost)
> set.seed(23)
> data(agaricus.train, package='xgboost')
> data(agaricus.test, package='xgboost')train <- agaricus.traintest <- agaricus.testbst <- xgboost(
>   data = train$data, label = train$label, max.depth = 2,
>   eta = 1, nround = 2,objective = "binary:logistic")pred <- predict(bst, test$data)
> #Hack to save an xgboost modelf1 <- tempfile()f2 <- tempfile()
> xgb.save(bst, f1)model_raw_bytes <- readBin(f1, what='raw', file.info(f)[1, "size"])
> unlink(f1)
> print(head(model_raw_bytes))
> saveRDS(model_raw_bytes, f2)
> #Hack to load an xgboostf3 <- tempfile()model_raw_bytes <- readRDS(f2)
> writeBin(model_raw_bytes, f3)model_2 <- xgb.load(f3)pred_2 <- predict(model_2, test$data)
> all.equal(pred_2, pred)
> unlink(f2)
> unlink(f3)
>
> Is there a way to pull the raw bytes of the xgboost model into R's
> memory, without first writing them to the disk?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tqchen/xgboost/issues/160#issuecomment-72391828>.
>


-- 
Sincerely,
------------------------------------------------
Tianqi Chen
Computer Science & Engineering, University of Washington

**Comment by tqchen** [comment]
As promised, this is an example of save/load from/to raw vector https://github.com/tqchen/xgboost/blob/master/R-package/demo/basic_walkthrough.R#L62

This is in the master branch and you can use the feature by install from github

**Comment by zachmayer** [comment]
Great, thank you.  That should be sufficient for me.  I'll just make a wrapper class that `raw.saves` the model after fitting, and `raw.loads` it before predicting.

**Comment by hetong007** [comment]
It is now supported better. Now every `xgb.Booster` object is a list of `handle` and `raw`. 
If `raw` is not `NULL`, you can directly save this part.
