### ISSUE TITLE
build fails on Mac OS X 10.9.5 w/Mac Ports' GCC 4.9

### ISSUE THREAD

**Issue by tantrev** [tqchen/xgboost#161]
Hello,

I am trying to install this wonderful software on my Mac but the compiling fails with the following stderr and stdout:

http://pastebin.com/raw.php?i=um05NHRS

Any ideas?  Thank you.

**Comment by tqchen** [comment]
You also need to change Makefile in https://github.com/tqchen/xgboost/blob/master/subtree/rabit/Makefile to use the same compiler

**Comment by tantrev** [comment]
That did the trick, thank you!

**Comment by tqchen** [comment]
I am updating the repo so that you do not have to do that. Changing the flag in the root Makefile will do. Can you try that again?

Thanks for reporting the issue

**Comment by tantrev** [comment]
Just tried and it worked perfectly.   :)

The only thing for newbies like myself is that you might want to update the documentation to show that the current Makefile reads "clang++" instead of "g++" as the xgboost homepage indicates.  Thanks again!

**Comment by tqchen** [comment]
oh.. I use clang to test the Makefile and forget to change it back.. Thanks for pointing out. The Makefile is correct now
