### ISSUE TITLE
Add References

### ISSUE THREAD

**Issue by dtsmith2001** [tqchen/xgboost#188]
Would you please add references to published papers so we can get further information?

**Comment by pommedeterresautee** [comment]
Presentation by @tqchen is in the ReadMe: 
http://homes.cs.washington.edu/~tqchen/pdf/BoostedTree.pdf

Other documentation is in the R vignettes:
https://github.com/tqchen/xgboost/blob/master/R-package/vignettes/xgboostPresentation.Rmd

And the bib is there:
https://github.com/tqchen/xgboost/blob/master/R-package/vignettes/xgboost.bib

Kind regards,
Michael

**Comment by pommedeterresautee** [comment]
Please close the issue if I answered your question.
