### ISSUE TITLE
xgboost cv vs normal training

### ISSUE THREAD

**Issue by farhanbaluch** [tqchen/xgboost#194]
-I am using the R package for xgboost on a dataset with some missing values =NA, R-version(3.1.2)
-It works when using the following (res is initially a list):

```
xg_mat <- xgb.DMatrix(res, missing=NA, label=y)
xgboost_mdl <- xgboost(data = xg_mat,
                       label = y,
                       ntreelimit = 2000,
                       eta = 0.1,
                       max_depth = 5,
                       subsample = 0.5,
                       nrounds=10)
```
I get a train-rmse for each iteration and everything looks ok. 

-But when I try:
```
xgb.cv(data=xg_mat,
       nfold=5, 
       nrounds=10, 
       label=y, 
       ntreelimit=2000, 
       eta=0.1, 
       max_depth=5, 
       subsample=0.5)
```
I get:
```
[0]	train-rmse:NaN+NA	test-rmse:NaN+NA
[1]	train-rmse:NaN+NA	test-rmse:NaN+NA
[2]	train-rmse:NaN+NA	test-rmse:NaN+NA
```
etc. 

Any pointers on why this might be happening? Am I missing a parameter or calling it incorrectly?

**Comment by pommedeterresautee** [comment]
Can you post full code and your dataset on a cloud so we can try wi

**Comment by fbnetflix** [comment]
Please close the issue I was just having an issue with converting a dataframe to xgb.DMatrix format. Its solved and working now. 

In case anyone comes across this I fixed the issue by converting the initial data frame object to a matrix and then Dmatrix as follows:

my_r_matrix <- data.matrix(my_data_frame)
my_D_matrix <- xgb.DMatrix(my_r_matrix, missing=NA, label=y)

and then running:
xgb.cv(data=my_D_matrix,
       nfold=5, 
       nrounds=10, 
       label=y, 
       ntreelimit=2000, 
       eta=0.1, 
       max_depth=5, 
       subsample=0.5)
