### ISSUE TITLE
Building xgboost on VS

### ISSUE THREAD

**Issue by ardeal** [tqchen/xgboost#195]
Hi Authors,
I am trying to run your XGBoost lib on VS 2013. I open xgboost\windows\xgboost.sln with my vs 2013 and build those 3 project on my vs. I got many errors. I have read the README.md in xgboost\windows folder, but unfortunately, it doesn't help at all.

can you share me your method to run your XGBoost lib on VS?

**Comment by tqchen** [comment]
Please make sure you are building x64 release. You should be able to directly build on VS.  I pushed a version that fixed the warnings in VS.

If things went wrong again, it would be great if you report the detailed errors

**Comment by tqchen** [comment]
I am closing this issue for now since there was no updates and the compilation went well on my testing machine. Please reopen if you have any problems

Thanks
