### ISSUE TITLE
add train caret package support

### ISSUE THREAD

**Issue by spedygiorgio** [tqchen/xgboost#197]
Thank you for releasing this great R package. Is it possible to integrate this package within the CARET package framework, so it becames callable by the train package?

**Comment by pommedeterresautee** [comment]
It seems that someone is already working on it : https://github.com/tqchen/xgboost/issues/160

Moreover, the missing piece (saving model in raw vector) is now implemented. Therefore I would say that it should come soon :-)

If I answered your question, please close this issue.

Kind regards,
Michael

**Comment by spedygiorgio** [comment]
ok thank you
