### ISSUE TITLE
Split MetaInfo During CV

### ISSUE THREAD

**Issue by BlindApe** [tqchen/xgboost#86]
After this issue:
https://github.com/tqchen/xgboost/issues/83

I'm trying to find a workaround to this problem:
My model fits desegregated cases but the metric error needs merging all cases of the same item code and computing a weighted metric at item code level.

If I don't use 'base_margin' slot, could I use it for this purpose? Or if I set any info in this slot xgboost use it as base margin automatically?

In case the answer be NO. Any tip to workaround?
Could be possible to introduce an 'id' and 'merging_group' slots for future versions?

Thank you!

**Comment by hetong007** [comment]
Finally it is fixed in [this commit](https://github.com/tqchen/xgboost/commit/5188bad8733e578fe9849fbd2ae89e9aee4bc1bc). 

Please test it with the following code:

```R
require(xgboost)
data(agaricus.train, package='xgboost')
dtrain <- xgb.DMatrix(agaricus.train$data, label = agaricus.train$label)
attr(dtrain, 'test') <- getinfo(dtrain, 'label')
str(attributes(dtrain))
slice(dtrain,1:20)
```
